// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDe58P1TGmaZ5V044Yt-EqhpnShbP-jzU',
    appId: '1:367225705603:web:232947ef62c97da64177b6',
    messagingSenderId: '367225705603',
    projectId: 'madad-21c30',
    authDomain: 'madad-21c30.firebaseapp.com',
    storageBucket: 'madad-21c30.firebasestorage.app',
    measurementId: 'G-DDLS6B3F2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfNQwqrj4tFVFFuPeOWwaesccla0etNlI',
    appId: '1:367225705603:android:c24130dd2065dcc44177b6',
    messagingSenderId: '367225705603',
    projectId: 'madad-21c30',
    storageBucket: 'madad-21c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOp-gK2ShJkTMMQ0ZAIycL_EVlrDSebUE',
    appId: '1:367225705603:ios:92bf92bff0456a914177b6',
    messagingSenderId: '367225705603',
    projectId: 'madad-21c30',
    storageBucket: 'madad-21c30.firebasestorage.app',
    iosClientId: '367225705603-5t4loonibeqbe93mk4s84r3949q2a4ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.redZone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOp-gK2ShJkTMMQ0ZAIycL_EVlrDSebUE',
    appId: '1:367225705603:ios:92bf92bff0456a914177b6',
    messagingSenderId: '367225705603',
    projectId: 'madad-21c30',
    storageBucket: 'madad-21c30.firebasestorage.app',
    iosClientId: '367225705603-5t4loonibeqbe93mk4s84r3949q2a4ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.redZone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDe58P1TGmaZ5V044Yt-EqhpnShbP-jzU',
    appId: '1:367225705603:web:e5f25a06c2eb74744177b6',
    messagingSenderId: '367225705603',
    projectId: 'madad-21c30',
    authDomain: 'madad-21c30.firebaseapp.com',
    storageBucket: 'madad-21c30.firebasestorage.app',
    measurementId: 'G-409RFYB8BH',
  );

}